### ISSUE TITLE
Automate role import into Ansible Galaxy

### ISSUE THREAD

**Issue by tobiashuste** [Helmholtz-UFZ/ansible-role-zammad#19]
Currently, it does not seem to automatically import new versions into Ansible galaxy. I would suggest to automate this procedure. According to the documentation of the Ansible Galaxy this could be done via Travis CI.

https://galaxy.ansible.com/docs/contributing/importing.html#import-roles-via-travis-ci

What do you think?

**Comment by Normo** [comment]
Good idea! Since we already use GitHub actions, I would try e.g. [robertdebock/galaxy-action](https://github.com/marketplace/actions/publish-ansible-role-to-galaxy) before switching to Travis CI.
