### ISSUE TITLE
Allow to optionally configure additional server directives in Nginx config

### ISSUE THREAD

**Issue by tobiashuste** [Helmholtz-UFZ/ansible-role-zammad#5]
In order to give the end user more flexibility, e.g. for handling multiple domains, handling domain changes, it would be nice to allow to configure additional server directives in the Nginx configuration.

I'd like to implement this that way, that a user gets the opportunity to add a complete server directive list which is then put into the configuration.

## Example

```yaml
zammad_nginx_additional_servers:
  - |
      server {
        listen 80;
        server_name zammad.example.com zammad-old.example.com;
        return 301 https://zammad.example.com$request_uri;
      }
  - |
      server {
        listen 443;
        server_name zammad-old.example.com;
        return 301 https://zammad.example.com$request_uri;
      }
  
```

**Comment by Normo** [comment]
#7 has been merged.
